# Site Settings
title: "Agile Methodology Tech Blog"
description: "Explore the best insights on Agile, Technology, and Software Development practices. Learn how to adopt Agile for organizational success."
url: "https://agilemethodology.github.io"
baseurl: ""

# Build Settings
markdown: kramdown
permalink: /blog/:title/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-analytics
  - jekyll-paginate
  - jekyll-archives
  - jekyll-minifier
  - jekyll-relative-links
  - jekyll-avatar
  - jekyll-tagging
  - jekyll-autoprefixer
  - jekyll-compress-images
  - jekyll-include-cache
  - jekyll-last-modified-at

# Sass Compression
sass:
  style: compressed

# SEO Configuration
author:
  name: "Agile Team"
  email: "dhaval2123mba@gmail.com"
  twitter: "brilworks_agile"
  linkedin: "brilworks"
  facebook: "brilworksAgile"
  instagram: "brilworksAgile"
  bio: "A dedicated team sharing Agile methodologies and software development insights to empower tech enthusiasts and professionals."
  location: "Ahmedabad, India"
  avatar: "/assets/images/avatar.jpg"

# Social Media Links
social_links:
  medium: "https://medium.com/@dhaval.info"
  linkedin: "https://www.linkedin.com/in/dhavalmakwana-/"
  github: "https://github.com/agilemethodology"
  instagram: "https://www.instagram.com/dhaval.info"

# Google Analytics
google_analytics: G-JZ3F961KTZ

# Default Page Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      share: true
      image: "/assets/images/default-og.jpg"
      image_alt: "Agile Methodology Tech Blog"
      canonical_url: true
      sitemap: true
      priority: 0.8
      changefreq: "weekly"
      
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    line_numbers: true

# Performance Optimization
timezone: UTC
encoding: UTF-8
paginate: 6
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

# Reading Experience
future: true
highlighter: rouge
paginate_path: "/page/:num/"
paginate_append: true

# Exclude Files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor
  - .git
  - .gitignore
  - .DS_Store

# Additional Metadata for SEO
meta_description: "Learn Agile principles, best practices, and technology trends with Agile Methodology Tech Blog. Gain insights to advance your career."
meta_keywords: "Agile methodology, project management, software development, agile transformation, technology insights"

# Sitemap Settings
sitemap:
  changefreq: "daily"
  priority: "1.0"
  exclude:
    - "/feed.xml"
    - "/404.html"
    - "/robots.txt"
    - "/humans.txt"
    - "/sitemap.xml"
  include:
    - "/blog/"
    - "/categories/"
    - "/tags/"
    - "/archives/"
  lastmod: true
  priority: true
  changefreq: true
  filename: "sitemap.xml"
  defaults:
    changefreq: "weekly"
    priority: 0.8
    lastmod: true

# Disqus Integration for Comments
disqus:
  shortname: agile-tech-blog

# Robots.txt
robots:
  disallow: 
    - /drafts/
    - /private/
    - /admin/
  allow: "/"

# Image Optimization
image_optim:
  pngout: false
  svgo: true
  jpegrecompress: true
  jpegoptim: true
  optipng: true
  gifsicle: true

# Structured Data
structured_data:
  organization:
    name: "Agile Methodology Tech Blog"
    url: "https://agilemethodology.github.io"
    logo: "/assets/images/logo.png"
    sameAs:
      - "https://github.com/agilemethodology"
      - "https://www.linkedin.com/in/dhavalmakwana-/"
      - "https://medium.com/@dhaval.info"
  breadcrumbs: true
  article: true
  blog: true

# Cache Settings
jekyll-include-cache:
  cache_dir: ".jekyll-cache"
  cache_include_dir: "_includes"

# Tagging Configuration
tag_page_layout: tag_page
tag_page_dir: tags
tag_page_title_prefix: "Tag: "
tag_page_title_suffix: " - Agile Methodology Tech Blog"

# Feed Configuration
feed:
  path: feed.xml
  posts_limit: 20
  excerpt_only: false
  categories:
    - agile
    - technology
    - software-development
  tags:
    - agile
    - scrum
    - kanban
    - devops
    - software-engineering

# Default front matter
default:
  date: true
  last_modified_at: true
  categories: []
  tags: []
  author: "Agile Team"
  image: "/assets/images/default-og-image.jpg"
  image_alt: "Agile Methodology"
  description: "Learn about Agile methodologies, best practices, and implementation strategies."
