# Site Settings
title: "Agile Methodology Tech Blog"
description: "Explore the best insights on Agile, Technology, and Software Development practices. Learn how to adopt Agile for organizational success."
url: "https://agilemethodology.github.io"
baseurl: ""

# Build Settings
markdown: kramdown
permalink: /blog/:title/

# Plugins
plugins:
<<<<<<< HEAD
  - jekyll-seo-tag # Adds metadata for better search engine indexing
  - jekyll-sitemap # Generates a sitemap.xml for search engines
  - jekyll-feed # Adds RSS feed for subscribers
  - jekyll-analytics # Enables Google Analytics tracking
  - jekyll-paginate # Enables pagination for blog posts
  - jekyll-archives # Creates archive pages by categories or tags
  - jekyll-breadcrumbs # Breadcrumbs are an essential UI element that helps users and search engines understand the structure of your website.
=======
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-analytics
  - jekyll-paginate
  - jekyll-archives
  - jekyll-minifier
  - jekyll-relative-links
  - jekyll-avatar
  - jekyll-tagging
  - jekyll-autoprefixer
  - jekyll-compress-images
  - jekyll-include-cache
  - jekyll-last-modified-at
>>>>>>> 2285e715f99f63230fdef3bfc51cd25e88439d1b

# Sass Compression
sass:
  style: compressed

# SEO Configuration
author:
  name: "Agile Team"
  email: "dhaval2123mba@gmail.com"
  twitter: "brilworks_agile"
  linkedin: "brilworks"
  facebook: "brilworksAgile"
  instagram: "brilworksAgile"
  bio: "A dedicated team sharing Agile methodologies and software development insights to empower tech enthusiasts and professionals."
<<<<<<< HEAD
  location: "Gujarat, India"
=======
  location: "Ahmedabad, India"
  avatar: "/assets/images/avatar.jpg"
>>>>>>> 2285e715f99f63230fdef3bfc51cd25e88439d1b

# Social Media Links
social_links:
  medium: "https://medium.com/@dhaval.info"
  linkedin: "https://www.linkedin.com/in/dhavalmakwana-/"
  github: "https://github.com/agilemethodology"
  instagram: "https://www.instagram.com/dhaval.info"

# Google Analytics
<<<<<<< HEAD
google_analytics: G-JZ3F961KTZ 
=======
google_analytics: G-JZ3F961KTZ
>>>>>>> 2285e715f99f63230fdef3bfc51cd25e88439d1b

# Default Page Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
<<<<<<< HEAD
      share: true # Add social sharing buttons on posts

# Performance Optimization
timezone: Asia/Kolkata
encoding: UTF-8
paginate: 5 # Number of posts per page for better navigation
=======
      share: true
      image: "/assets/images/default-og.jpg"
      image_alt: "Agile Methodology Tech Blog"
      canonical_url: true
      sitemap: true
      priority: 0.8
      changefreq: "weekly"
      
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    line_numbers: true

# Performance Optimization
timezone: UTC
encoding: UTF-8
paginate: 6
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
>>>>>>> 2285e715f99f63230fdef3bfc51cd25e88439d1b

# Reading Experience
future: true
highlighter: rouge
<<<<<<< HEAD
paginate_path: "/page:num/"
=======
paginate_path: "/page/:num/"
paginate_append: true
>>>>>>> 2285e715f99f63230fdef3bfc51cd25e88439d1b

# Exclude Files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor
<<<<<<< HEAD

# Additional Metadata for SEO
meta_description: "{% if page.description %}{{ page.description }}{% else %}Learn Agile principles, best practices, and technology trends with Agile Methodology Tech Blog.{% endif %}"
title: "{% if page.title %}{{ page.title }} - Agile Methodology Tech Blog{% else %}Agile Methodology Tech Blog{% endif %}"
meta_keywords: "Agile methodology, project management, software development, agile transformation, technology insights"
<link rel="canonical" href="{{ page.url | absolute_url }}">

# Sitemap Settings
sitemap:
  changefreq: "weekly"
  priority: "1.0"
=======
  - .git
  - .gitignore
  - .DS_Store

# Additional Metadata for SEO
meta_description: "Learn Agile principles, best practices, and technology trends with Agile Methodology Tech Blog. Gain insights to advance your career."
meta_keywords: "Agile methodology, project management, software development, agile transformation, technology insights"

# Sitemap Settings
sitemap:
  changefreq: "daily"
  priority: "1.0"
  exclude:
    - "/feed.xml"
    - "/404.html"
    - "/robots.txt"
    - "/humans.txt"
    - "/sitemap.xml"
  include:
    - "/blog/"
    - "/categories/"
    - "/tags/"
    - "/archives/"
  lastmod: true
  priority: true
  changefreq: true
  filename: "sitemap.xml"
  defaults:
    changefreq: "weekly"
    priority: 0.8
    lastmod: true
>>>>>>> 2285e715f99f63230fdef3bfc51cd25e88439d1b

# Disqus Integration for Comments
disqus:
  shortname: agile-tech-blog

# Robots.txt
robots:
  disallow: 
    - /drafts/
<<<<<<< HEAD
allow: "/"

# Advanced Caching (optional)
jekyll_assets:
  compress: true

=======
    - /private/
    - /admin/
  allow: "/"

# Image Optimization
image_optim:
  pngout: false
  svgo: true
  jpegrecompress: true
  jpegoptim: true
  optipng: true
  gifsicle: true

# Structured Data
structured_data:
  organization:
    name: "Agile Methodology Tech Blog"
    url: "https://agilemethodology.github.io"
    logo: "/assets/images/logo.png"
    sameAs:
      - "https://github.com/agilemethodology"
      - "https://www.linkedin.com/in/dhavalmakwana-/"
      - "https://medium.com/@dhaval.info"
  breadcrumbs: true
  article: true
  blog: true

# Cache Settings
jekyll-include-cache:
  cache_dir: ".jekyll-cache"
  cache_include_dir: "_includes"

# Tagging Configuration
tag_page_layout: tag_page
tag_page_dir: tags
tag_page_title_prefix: "Tag: "
tag_page_title_suffix: " - Agile Methodology Tech Blog"

# Feed Configuration
feed:
  path: feed.xml
  posts_limit: 20
  excerpt_only: false
  categories:
    - agile
    - technology
    - software-development
  tags:
    - agile
    - scrum
    - kanban
    - devops
    - software-engineering

# Default front matter
default:
  date: true
  last_modified_at: true
  categories: []
  tags: []
  author: "Agile Team"
  image: "/assets/images/default-og-image.jpg"
  image_alt: "Agile Methodology"
  description: "Learn about Agile methodologies, best practices, and implementation strategies."
>>>>>>> 2285e715f99f63230fdef3bfc51cd25e88439d1b
