# Site Settings
title: Agile Methodology Tech Blog
description: Insights on Technology, Agile, and Software Development
url: "https://agilemethodology.github.io"
baseurl: ""

# Build Settings
markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Sass Compression
sass:
  style: compressed

# SEO Configuration
author:
  name: Agile Team
  email: dhaval2123mba@gmail.com

# Social Media Links
social:
  github: brilworks
  linkedin: brilworks

# Default Page Settings
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

# Performance Optimization
timezone: Asia/Kolkata
encoding: UTF-8

# Reading Experience
future: true
highlighter: rouge

# Exclude Files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE