title: "Agile Methodology Guide"
description: "Your go-to guide for Agile methodologies, principles, and practices."
url: "https://agilemethodology.github.io"
baseurl: "" # leave as empty for root-level site
theme: jekyll-theme-minimal
markdown: kramdown
